apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-api-users
  name: udagram-api-users
spec:
  replicas: 2
  template:
    metadata:
      labels:
        service: udagram-api-users
    spec:
      containers:
      - image: pradeeppaidock/udagram-api-users
        name: udagram-api-users
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: POSTGRES_HOST
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: POSTGRES_DB
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: JWT_SECRET
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: URL
      restartPolicy: Always
